### ISSUE TITLE
taproot address send transaction error:non-mandatory-script-verify-flag (Invalid Schnorr signature) 

### ISSUE THREAD

**Issue by yplong** [mrtnetwork/bitcoin#2]
```
func main() {
 // Private key of the UTXO owner
 privateKey, _ := keypair.NewECPrivateFromWIF("91qdf1RH6UMZwZTnHUJ3RSiGSZ5EAxvW2FgYFV2HeaLnqZQh4zx")

 // Address we want to spend from
 fromAddr := privateKey.GetPublic().ToTaprootAddress()

 // Create an input
 // Insert transaction ID and index of UTXO
 sigTxin1 := scripts.NewTxInput("21c3bbc77f6193890f9e8b4b4fad765a9e72735a7aac551f0ccb28943b8830b5", 0)

 // Address we want to send funds to
 addr, _ := address.P2PKHAddressFromAddress("n4bkvTyU1dVdzsrhWBqBw8fEMbHjJvtmJR")

 // Create an output: Send 3000 to `n4bkvTyU1dVdzsrhWBqBw8fEMbHjJvtmJR`
 txout := scripts.NewTxOutput(
  big.NewInt(1000),
  addr.ToScriptPubKey(),
 )

 // Create a transaction
 tx := scripts.NewBtcTransaction(
  []*scripts.TxInput{sigTxin1},
  []*scripts.TxOutput{txout},
  true, // The transaction contains one or more segwit UTXOs
 )

 // Get the transaction digest for signing input at index 0
 // Arguments:
 // - Index 0
 // - The scriptPubkeys that correspond to all the inputs/UTXOs
 // - The amounts that correspond to all the inputs/UTXOs
 // - Ext_flag: Extension mechanism, default is 0; 1 is for script spending (BIP342)
 // - Script: The script that we are spending when ext_flag is 1
 digest := tx.GetTransactionTaprootDigest(0, []*scripts.Script{fromAddr.ToScriptPubKey()}, []*big.Int{big.NewInt(3500)}, 0, scripts.NewScript(), constant.TAPROOT_SIGHASH_ALL)

 // Sign the transaction
 // Arguments:
 // - Transaction digest related to the index
 // - Signature Hash Type (TAPROOT_SIGHASH_ALL)
 // - Script path (tapleafs)
 // - Tweak: Note that we don't use tapleafs script in this transaction, so the tweak should be set to False
 sig := privateKey.SignTaprootTransaction(digest, constant.TAPROOT_SIGHASH_ALL, []interface{}{}, false)

 // Create a witness signature and set it to the transaction at the current index
 witness := scripts.NewTxWitnessInput(sig)
 tx.Witnesses = append(tx.Witnesses, witness)

 // Transaction ID
 tx.TxId()

 // In this case, the transaction is segwit, and we must use GetVSize for transaction size
 tx.GetVSize()

 // Transaction digest ready for broadcast
 digestHex := tx.Serialize()

 api := provider.SelectApi(provider.MempoolApi, &address.TestnetNetwork)
 trId, err := api.SendRawTransaction(digestHex)
 if err != nil {
  fmt.Println("err:", err)
 }
 fmt.Println("trid:", trId)

}
```

Using the Spend P2TR UTXO code example in README.md (wif has been changed to my own input hash, etc.), sendrawtransaction RPC error is raised: {"code":-26,"message":"non-mandatory-script-verify-flag (Invalid Schnorr signature) "} Error, is there something I set incorrectly?

**Comment by mrtnetwork** [comment]
when you use ```  privateKey.GetPublic().ToTaprootAddress() ``` This mean u create an address with the tweaked public key and when you want to send a transaction should you set tweak true in this case ```sig := privateKey.SignTaprootTransaction(digest, constant.TAPROOT_SIGHASH_ALL, []interface{}{}, false) ``` set ```false``` to ``` true ```

**Comment by mrtnetwork** [comment]
> ```
> func main() {
>  // Private key of the UTXO owner
>  privateKey, _ := keypair.NewECPrivateFromWIF("91qdf1RH6UMZwZTnHUJ3RSiGSZ5EAxvW2FgYFV2HeaLnqZQh4zx")
> 
>  // Address we want to spend from
>  fromAddr := privateKey.GetPublic().ToTaprootAddress()
> 
>  // Create an input
>  // Insert transaction ID and index of UTXO
>  sigTxin1 := scripts.NewTxInput("21c3bbc77f6193890f9e8b4b4fad765a9e72735a7aac551f0ccb28943b8830b5", 0)
> 
>  // Address we want to send funds to
>  addr, _ := address.P2PKHAddressFromAddress("n4bkvTyU1dVdzsrhWBqBw8fEMbHjJvtmJR")
> 
>  // Create an output: Send 3000 to `n4bkvTyU1dVdzsrhWBqBw8fEMbHjJvtmJR`
>  txout := scripts.NewTxOutput(
>   big.NewInt(1000),
>   addr.ToScriptPubKey(),
>  )
> 
>  // Create a transaction
>  tx := scripts.NewBtcTransaction(
>   []*scripts.TxInput{sigTxin1},
>   []*scripts.TxOutput{txout},
>   true, // The transaction contains one or more segwit UTXOs
>  )
> 
>  // Get the transaction digest for signing input at index 0
>  // Arguments:
>  // - Index 0
>  // - The scriptPubkeys that correspond to all the inputs/UTXOs
>  // - The amounts that correspond to all the inputs/UTXOs
>  // - Ext_flag: Extension mechanism, default is 0; 1 is for script spending (BIP342)
>  // - Script: The script that we are spending when ext_flag is 1
>  digest := tx.GetTransactionTaprootDigest(0, []*scripts.Script{fromAddr.ToScriptPubKey()}, []*big.Int{big.NewInt(3500)}, 0, scripts.NewScript(), constant.TAPROOT_SIGHASH_ALL)
> 
>  // Sign the transaction
>  // Arguments:
>  // - Transaction digest related to the index
>  // - Signature Hash Type (TAPROOT_SIGHASH_ALL)
>  // - Script path (tapleafs)
>  // - Tweak: Note that we don't use tapleafs script in this transaction, so the tweak should be set to False
>  sig := privateKey.SignTaprootTransaction(digest, constant.TAPROOT_SIGHASH_ALL, []interface{}{}, false)
> 
>  // Create a witness signature and set it to the transaction at the current index
>  witness := scripts.NewTxWitnessInput(sig)
>  tx.Witnesses = append(tx.Witnesses, witness)
> 
>  // Transaction ID
>  tx.TxId()
> 
>  // In this case, the transaction is segwit, and we must use GetVSize for transaction size
>  tx.GetVSize()
> 
>  // Transaction digest ready for broadcast
>  digestHex := tx.Serialize()
> 
>  api := provider.SelectApi(provider.MempoolApi, &address.TestnetNetwork)
>  trId, err := api.SendRawTransaction(digestHex)
>  if err != nil {
>   fmt.Println("err:", err)
>  }
>  fmt.Println("trid:", trId)
> 
> }
> ```
> 
> Using the Spend P2TR UTXO code example in README.md (wif has been changed to my own input hash, etc.), sendrawtransaction RPC error is raised: {"code":-26,"message":"non-mandatory-script-verify-flag (Invalid Schnorr signature) "} Error, is there something I set incorrectly?

when you use ```  privateKey.GetPublic().ToTaprootAddress() ``` This mean u create an address with the tweaked public key and when you want to send a transaction should you set tweak true in this case ```sig := privateKey.SignTaprootTransaction(digest, constant.TAPROOT_SIGHASH_ALL, []interface{}{}, false) ``` set ```false``` to ``` true ```

**Comment by yplong** [comment]
> > ```
> > func main() {
> >  // Private key of the UTXO owner
> >  privateKey, _ := keypair.NewECPrivateFromWIF("91qdf1RH6UMZwZTnHUJ3RSiGSZ5EAxvW2FgYFV2HeaLnqZQh4zx")
> > 
> >  // Address we want to spend from
> >  fromAddr := privateKey.GetPublic().ToTaprootAddress()
> > 
> >  // Create an input
> >  // Insert transaction ID and index of UTXO
> >  sigTxin1 := scripts.NewTxInput("21c3bbc77f6193890f9e8b4b4fad765a9e72735a7aac551f0ccb28943b8830b5", 0)
> > 
> >  // Address we want to send funds to
> >  addr, _ := address.P2PKHAddressFromAddress("n4bkvTyU1dVdzsrhWBqBw8fEMbHjJvtmJR")
> > 
> >  // Create an output: Send 3000 to `n4bkvTyU1dVdzsrhWBqBw8fEMbHjJvtmJR`
> >  txout := scripts.NewTxOutput(
> >   big.NewInt(1000),
> >   addr.ToScriptPubKey(),
> >  )
> > 
> >  // Create a transaction
> >  tx := scripts.NewBtcTransaction(
> >   []*scripts.TxInput{sigTxin1},
> >   []*scripts.TxOutput{txout},
> >   true, // The transaction contains one or more segwit UTXOs
> >  )
> > 
> >  // Get the transaction digest for signing input at index 0
> >  // Arguments:
> >  // - Index 0
> >  // - The scriptPubkeys that correspond to all the inputs/UTXOs
> >  // - The amounts that correspond to all the inputs/UTXOs
> >  // - Ext_flag: Extension mechanism, default is 0; 1 is for script spending (BIP342)
> >  // - Script: The script that we are spending when ext_flag is 1
> >  digest := tx.GetTransactionTaprootDigest(0, []*scripts.Script{fromAddr.ToScriptPubKey()}, []*big.Int{big.NewInt(3500)}, 0, scripts.NewScript(), constant.TAPROOT_SIGHASH_ALL)
> > 
> >  // Sign the transaction
> >  // Arguments:
> >  // - Transaction digest related to the index
> >  // - Signature Hash Type (TAPROOT_SIGHASH_ALL)
> >  // - Script path (tapleafs)
> >  // - Tweak: Note that we don't use tapleafs script in this transaction, so the tweak should be set to False
> >  sig := privateKey.SignTaprootTransaction(digest, constant.TAPROOT_SIGHASH_ALL, []interface{}{}, false)
> > 
> >  // Create a witness signature and set it to the transaction at the current index
> >  witness := scripts.NewTxWitnessInput(sig)
> >  tx.Witnesses = append(tx.Witnesses, witness)
> > 
> >  // Transaction ID
> >  tx.TxId()
> > 
> >  // In this case, the transaction is segwit, and we must use GetVSize for transaction size
> >  tx.GetVSize()
> > 
> >  // Transaction digest ready for broadcast
> >  digestHex := tx.Serialize()
> > 
> >  api := provider.SelectApi(provider.MempoolApi, &address.TestnetNetwork)
> >  trId, err := api.SendRawTransaction(digestHex)
> >  if err != nil {
> >   fmt.Println("err:", err)
> >  }
> >  fmt.Println("trid:", trId)
> > 
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Using the Spend P2TR UTXO code example in README.md (wif has been changed to my own input hash, etc.), sendrawtransaction RPC error is raised: {"code":-26,"message":"non-mandatory-script-verify-flag (Invalid Schnorr signature) "} Error, is there something I set incorrectly?
> 
> when you use ` privateKey.GetPublic().ToTaprootAddress()` This mean u create an address with the tweaked public key and when you want to send a transaction should you set tweak true in this case `sig := privateKey.SignTaprootTransaction(digest, constant.TAPROOT_SIGHASH_ALL, []interface{}{}, false) ` set `false` to `true`

I still can't modify it according to what you said. The above code can be executed in your place. Can you send the transaction normally?

**Comment by mrtnetwork** [comment]
> > > ```
> > > func main() {
> > >  // Private key of the UTXO owner
> > >  privateKey, _ := keypair.NewECPrivateFromWIF("91qdf1RH6UMZwZTnHUJ3RSiGSZ5EAxvW2FgYFV2HeaLnqZQh4zx")
> > > 
> > >  // Address we want to spend from
> > >  fromAddr := privateKey.GetPublic().ToTaprootAddress()
> > > 
> > >  // Create an input
> > >  // Insert transaction ID and index of UTXO
> > >  sigTxin1 := scripts.NewTxInput("21c3bbc77f6193890f9e8b4b4fad765a9e72735a7aac551f0ccb28943b8830b5", 0)
> > > 
> > >  // Address we want to send funds to
> > >  addr, _ := address.P2PKHAddressFromAddress("n4bkvTyU1dVdzsrhWBqBw8fEMbHjJvtmJR")
> > > 
> > >  // Create an output: Send 3000 to `n4bkvTyU1dVdzsrhWBqBw8fEMbHjJvtmJR`
> > >  txout := scripts.NewTxOutput(
> > >   big.NewInt(1000),
> > >   addr.ToScriptPubKey(),
> > >  )
> > > 
> > >  // Create a transaction
> > >  tx := scripts.NewBtcTransaction(
> > >   []*scripts.TxInput{sigTxin1},
> > >   []*scripts.TxOutput{txout},
> > >   true, // The transaction contains one or more segwit UTXOs
> > >  )
> > > 
> > >  // Get the transaction digest for signing input at index 0
> > >  // Arguments:
> > >  // - Index 0
> > >  // - The scriptPubkeys that correspond to all the inputs/UTXOs
> > >  // - The amounts that correspond to all the inputs/UTXOs
> > >  // - Ext_flag: Extension mechanism, default is 0; 1 is for script spending (BIP342)
> > >  // - Script: The script that we are spending when ext_flag is 1
> > >  digest := tx.GetTransactionTaprootDigest(0, []*scripts.Script{fromAddr.ToScriptPubKey()}, []*big.Int{big.NewInt(3500)}, 0, scripts.NewScript(), constant.TAPROOT_SIGHASH_ALL)
> > > 
> > >  // Sign the transaction
> > >  // Arguments:
> > >  // - Transaction digest related to the index
> > >  // - Signature Hash Type (TAPROOT_SIGHASH_ALL)
> > >  // - Script path (tapleafs)
> > >  // - Tweak: Note that we don't use tapleafs script in this transaction, so the tweak should be set to False
> > >  sig := privateKey.SignTaprootTransaction(digest, constant.TAPROOT_SIGHASH_ALL, []interface{}{}, false)
> > > 
> > >  // Create a witness signature and set it to the transaction at the current index
> > >  witness := scripts.NewTxWitnessInput(sig)
> > >  tx.Witnesses = append(tx.Witnesses, witness)
> > > 
> > >  // Transaction ID
> > >  tx.TxId()
> > > 
> > >  // In this case, the transaction is segwit, and we must use GetVSize for transaction size
> > >  tx.GetVSize()
> > > 
> > >  // Transaction digest ready for broadcast
> > >  digestHex := tx.Serialize()
> > > 
> > >  api := provider.SelectApi(provider.MempoolApi, &address.TestnetNetwork)
> > >  trId, err := api.SendRawTransaction(digestHex)
> > >  if err != nil {
> > >   fmt.Println("err:", err)
> > >  }
> > >  fmt.Println("trid:", trId)
> > > 
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Using the Spend P2TR UTXO code example in README.md (wif has been changed to my own input hash, etc.), sendrawtransaction RPC error is raised: {"code":-26,"message":"non-mandatory-script-verify-flag (Invalid Schnorr signature) "} Error, is there something I set incorrectly?
> > 
> > 
> > when you use ` privateKey.GetPublic().ToTaprootAddress()` This mean u create an address with the tweaked public key and when you want to send a transaction should you set tweak true in this case `sig := privateKey.SignTaprootTransaction(digest, constant.TAPROOT_SIGHASH_ALL, []interface{}{}, false) ` set `false` to `true`
> 
> I still can't modify it according to what you said. The above code can be executed in your place. Can you send the transaction normally?

i checked your transaction
set tweak ```true```
```
sig := privateKey.SignTaprootTransaction(digest, constant.TAPROOT_SIGHASH_ALL, []interface{}{}, true) // set to tue

```
you must set your all Utxo amount of transaction in this case 
you set ```3500``` satoshi but when i check you tx in id i got ```3000```[blockcypher](https://api.blockcypher.com/v1/btc/test3/txs/21c3bbc77f6193890f9e8b4b4fad765a9e72735a7aac551f0ccb28943b8830b5?limit=50&includeHex=true)
```
digest := tx.GetTransactionTaprootDigest(0, []*scripts.Script{fromAddr.ToScriptPubKey()}, []*big.Int{big.NewInt(3000)}, 0, scripts.NewScript(), constant.TAPROOT_SIGHASH_ALL)

```

mempool test result 

```
{"result":[{"txid":"58d863953e6046efc35bd4ebd6483c56cbf2dbb506abcb478ca8d84fd2307220","wtxid":"d628d34d934c16cbe3a084501fcb4853d3581b99fac85cf560fea150ebc7ffc3","allowed":true,"vsize":102,"fees":{"base":0.00002000,"effective-feerate":0.00019607,"effective-includes":["d628d34d934c16cbe3a084501fcb4853d3581b99fac85cf560fea150ebc7ffc3"]}}],"error":null,"id":"123"}

```

**Comment by mrtnetwork** [comment]
I apologize for confusing you, I wrote the readme wrong, and now it has been corrected

**Comment by yplong** [comment]
> I apologize for confusing you, I wrote the readme wrong, and now it has been corrected

Thank you very much. Problem solved
