### ISSUE TITLE
load transaction from a rawTrx,I found some txInputs with large txIndex

### ISSUE THREAD

**Issue by ElleryHao** [mrtnetwork/bitcoin#5]
first, I build a trx with newBtcTransaction,in which the txinput is like : utxo id: 326a778ebde5c6926f0507bdc9ebc84962588efc094c734f7f58e5d7b633fb0c, txIndex is 2, utxo amount 11971

second, I have this trx serilized and get a string

third, I call btcTransactionFromRaw, but I found that txIndex is 2<<24, maybe because my machine is the one need to call reversedByte

**Comment by mrtnetwork** [comment]
> first, I build a trx with newBtcTransaction,in which the txinput is like : utxo id: 326a778ebde5c6926f0507bdc9ebc84962588efc094c734f7f58e5d7b633fb0c, txIndex is 2, utxo amount 11971
> 
> second, I have this trx serilized and get a string
> 
> third, I call btcTransactionFromRaw, but I found that txIndex is 2<<24, maybe because my machine is the one need to call reversedByte

i try to check as soon as possible

**Comment by mrtnetwork** [comment]
> first, I build a trx with newBtcTransaction,in which the txinput is like : utxo id: 326a778ebde5c6926f0507bdc9ebc84962588efc094c734f7f58e5d7b633fb0c, txIndex is 2, utxo amount 11971
> 
> second, I have this trx serilized and get a string
> 
> third, I call btcTransactionFromRaw, but I found that txIndex is 2<<24, maybe because my machine is the one need to call reversedByte

thanks, for report that
